const page = await browser.getPage("main");
await page.setViewportSize({ width: 1400, height: 900 });
await page.goto("http://localhost:17374/projects/proj_xfhduummc3/threads/thr_em7hmw2zzh", { waitUntil: "load" });
await page.waitForTimeout(7000);
const link = page.getByRole("link", { name: /this link/ }).last();
console.log("href attr:", await link.getAttribute("href"));
await link.click();
await page.waitForTimeout(3000);
const btn = page.getByRole("button", { name: /open in editor/i }).first();
console.log("button label:", await btn.getAttribute("aria-label"));
await btn.hover();
await page.waitForTimeout(800);
await saveScreenshot(await page.screenshot(), "1182-hover-open-in-editor.png");
await btn.click();
await page.waitForTimeout(3500);
await saveScreenshot(await page.screenshot(), "1182-open-in-editor.png");
const t = await page.evaluate(() => document.body.innerText);
const i = t.indexOf("Failed to open");
console.log("toast text:", JSON.stringify(i >= 0 ? t.slice(i, i + 300) : t.slice(-400)));
