const fs = require('node:fs');
const path = require('node:path');
const { createRequire } = require('node:module');
const root = path.resolve(process.argv[2]);
const req = createRequire(path.join(root, 'apps/app/package.json'));
const ts = req('typescript');
const React = req('react');
const { renderToStaticMarkup } = req('react-dom/server');
const source = fs.readFileSync(path.join(root, 'apps/app/src/components/sidebar/ProjectRow.tsx'), 'utf8');
const start = source.indexOf('{headerActions ? (', source.indexOf('const projectActions ='));
const end = source.indexOf(') : null}', start) + ') : null}'.length;
if (start < 0 || end < start) throw new Error('Header slot not found');
const constants = fs.readFileSync(path.join(root, 'apps/app/src/components/ui/sidebar-hover-actions.ts'), 'utf8');
const constant = name => {
  const match = constants.match(new RegExp('export const ' + name + '\\s*=\\s*"([^"]+)"'));
  if (!match) throw new Error('Constant not found: ' + name);
  return match[1];
};
const jsx = 'return <>' + source.slice(start, end) + '</>;';
const compiled = ts.transpileModule('function fixture(){' + jsx + '}', {compilerOptions:{jsx:ts.JsxEmit.React, target:ts.ScriptTarget.ES2022}}).outputText;
const make = new Function('React','headerActions','headerActionsOpen','SIDEBAR_HOVER_ACTIONS_CLASS','SIDEBAR_HOVER_ACTIONS_MOBILE_ALWAYS_VALUE',compiled + ';return fixture();');
const control = React.createElement('button', {'aria-label':'Display options', id:'display'}, 'Display options');
const markup = renderToStaticMarkup(make(React, control, false, constant('SIDEBAR_HOVER_ACTIONS_CLASS'), constant('SIDEBAR_HOVER_ACTIONS_MOBILE_ALWAYS_VALUE')));
const theme = fs.readFileSync(path.join(root, 'apps/app/src/components/ui/theme.css'), 'utf8');
const cssStart = theme.indexOf('  .bb-sidebar-hover-actions {');
const cssEnd = theme.indexOf('  [data-sidebar-sticky-stack]', cssStart);
if (cssStart < 0 || cssEnd < 0) throw new Error('Hover CSS not found');
const css = theme.slice(cssStart, cssEnd);
const html = '<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>' + css + '\nbody{font:16px system-ui;margin:24px;background:#fafaf8;color:#1a1a1a}section{border:1px solid #ccc;padding:16px}button{font:inherit;padding:8px}.bb-sidebar-hover-actions-row{display:flex;align-items:center;justify-content:space-between;gap:8px}</style></head><body><h1>Project header probe</h1><p>Isolated production wrapper and hover CSS. Simplified label and button.</p><section class="bb-sidebar-hover-actions-row"><strong>QA project</strong>' + markup + '</section><p id="result">No tap received</p><script>document.querySelector("#display").onclick=()=>document.querySelector("#result").textContent="Tap received";</script></body></html>';
fs.writeFileSync(process.argv[3], html);
console.log(JSON.stringify({wrapper:markup,source:'ProjectRow.tsx',css:'theme.css'}));
