const page = await browser.getPage("main");
await page.setViewportSize({width: 1400, height: 900});
await page.goto("http://localhost:14008/projects/proj_87t2bdjuvh", {waitUntil: "networkidle"});
await page.waitForTimeout(2500);
const trigger = page.locator('button', { hasText: 'Work locally' }).first();
await trigger.click();
await page.waitForTimeout(1200);
await saveScreenshot(await page.screenshot(), "1595-picker-plain.png");
const items = await page.evaluate(() => [...document.querySelectorAll('[role="menuitem"],[role="menuitemradio"],[role="option"]')].map(e => ({text: e.innerText.trim().replace(/\n/g,' | '), disabled: e.getAttribute('aria-disabled') ?? e.getAttribute('data-disabled')})));
console.log(JSON.stringify(items, null, 1));
