import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const { chromium } = require(`${process.env.HOME}/.nvm/versions/node/v24.18.0/lib/node_modules/dev-browser/node_modules/playwright`);
const APP=process.env.APP, PROJECT=process.env.PROJECT;
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const page = await context.newPage();
page.on("console", m => { if (m.type()==="error") console.log("console.error:", m.text().slice(0,200)); });
page.on("pageerror", e => console.log("pageerror:", e.message));
const t=Date.now();
await page.goto(`${APP}/projects/${PROJECT}`, { waitUntil: "load", timeout: 60000 });
console.log("loaded in", Date.now()-t);
await new Promise(r=>setTimeout(r,8000));
console.log("body:", (await page.evaluate(()=>document.body.innerText)).slice(0,600));
console.log("buttons:", await page.getByRole("button").allTextContents().then(x=>x.slice(0,30)));
console.log("toggle sidebar count:", await page.getByRole("button", { name: "Toggle Sidebar" }).count());
await page.getByRole("button", { name: "Toggle Sidebar" }).first().click({ timeout: 5000 }).catch(e=>console.log("toggle click failed", e.message.slice(0,100)));
await new Promise(r=>setTimeout(r,1500));
console.log("links:", await page.getByRole("link").evaluateAll(ls=>ls.map(l=>l.getAttribute("aria-label")||l.textContent).slice(0,30)));
await page.screenshot({ path: "/tmp/bb-reports/issues/1303/verify/v2-diag.png" });
await browser.close();
